management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  application:
    name: ORGANIZATION-SERVICE




